- .github/workflows/devdeploy.yml
- Dockerfile
- nais-dev.yaml
- nginx.conf
- package.json
- src/app.tsx
Denne endringen gjør at når en commit skjer på master, vil GitHub Actions sette i gang en prosess med å bygge applikasjonen, lage et Docker-image av bygget, dytte det til GitHub Package Registry og sette det på NAIS. Applikasjonen er deretter tilgjengelig på https://tjenester-q1.nav.no/sykepengesok
> Bruk GitHub Actions

- cypress/integration/arbeidsledig_100.ts
- cypress/integration/arbeidstaker_100.ts
- cypress/integration/arbeidstaker_50.ts
- cypress/integration/arbeidstaker_behandlingsdager.ts
- cypress/integration/frilanser_100.ts
- cypress/integration/opphold_utland.ts
- cypress/integration/veldig_lang_soknad.ts
Disse må settes opp på nytt når kvitteringene er på plass
> Fjerner kvittering testene

- .gitignore
- public/dev-frontendlogger.js
- public/index.html
- sourcemap-debug.js
- src/index.tsx
https://github.com/flatpickr/flatpickr/issues/1904
> Legg inn tomt styleheet som workaround

- src/components/kvittering/arbeidstaker.tsx
Etter endring iht ettersending trengs ikke denne lenger
> Fjerner unødvendig kall til finnMottaker.

- src/components/sporsmal/typer/ja-nei-input.tsx
- src/components/sporsmal/typer/ja-nei-radio.tsx
- src/components/sporsmal/typer/radio-komp.tsx
> I IE 11 fyres ikke onchange på første klikket

- src/components/sporsmal/typer/tall-komp.tsx
Stopper de fleste i døra når de vil legge inn prosent med desimaltall, må ha en fiks på serversiden også
> Legg til step=1 for prosentsvar

- .env
- cypress/support/index.ts
- nais-dev-gcp.yaml
- nais-labs.yaml
- nais-prod.yaml
- nais-q1.yaml
- src/components/endreknapp/endreknapp.tsx
- src/components/ettersending/ettersending.tsx
- src/components/kvittering/arbeidstaker.tsx
- src/components/sporsmal/sporsmal-form/avbryt-soknad.ts
- src/components/sporsmal/sporsmal-form/sporsmal-form.tsx
- src/components/status/statuspanel.tsx
- src/data/data-fetcher.tsx
- src/data/mock/index.ts
- src/pages/opprett-utland/opprett-utland.tsx
- src/utils/environment.ts
- src/utils/fetcher.ts
This reverts commit 2ded2fdf3cf8434eb0f8112e15400f9b6dff7885.
> Revert "reverter tilbake til syfoapi"

- src/components/feiloppsummering/feil-oppsummering.tsx
- src/components/soknader/teaser/fremtidige-soknader-teaser.tsx
- src/components/soknader/teaser/teaser.tsx
- src/components/soknader/teaser/tidligere-soknader-teaser.tsx
- src/components/soknader/teaser/utgatt-soknader-teaser.tsx
- src/components/sporsmal/sporsmal-form/sporsmal-form.tsx
- src/components/sporsmal/sporsmal-steg/steg.tsx
Det gjenstår å "standardisere" attributtnavn også, men slik jeg forstår det er ikke dette like viktig.
Dette er grunnlaget for de nye eventnavna: https://github.com/navikt/analytics-taxonomy/tree/main/events
> Endrer navn på events

- package-lock.json
- src/components/animate-on-mount.tsx
Co-authored-by: Bjørn Inge Kulsveen <bjorn.inge.kulsveen@nav.no>
> Ikke scroll ved svart spørsmål

- cypress/integration/run-0/arbeidstaker_50.ts
- cypress/integration/run-1/feilmeldinger.ts
- src/data/mock/data/reisetilskudd.ts
- src/data/mock/data/soknader-integration.ts
- src/data/mock/data/soknader-opplaering.ts
- Endret rekkefølge på spørsmål i mock-data  sånn at rekkefølgen tilsvarer
endringer i syfosoknad.
- Oppdatert Cypress-tester.
> Endre rekkefølge på spørsmål i mock-data

- src/components/sporsmal/bjorn/bjorn-under-tittel.tsx
Spørsmålstaggen er kun i arbeidstakersøkna
> Viser bjørn på ferie spørsmål på gradert rt

- nais-dev-gcp.yaml
- nais-prod-gcp.yaml
- server/src/index.ts
- src/components/hotjar-trigger.tsx
- src/data/mock/index.ts
- src/pages/kvittering/kvittering-side.tsx
- src/utils/environment.ts
This reverts commit 6949b16847a1ca50dd466ac4cdb89b3955e7734b.
> Revert "hotjar rekruttering (#395)"

- nais-dev-gcp.yaml
- nais-prod-gcp.yaml
- server/src/index.ts
- src/components/hotjar-trigger.tsx
- src/data/mock/index.ts
- src/pages/kvittering/kvittering-side.tsx
- src/utils/environment.ts
This reverts commit 32de1cf600b64657de9406a134939666c7e5bd27.
> Revert "Revert "hotjar rekruttering (#395)" (#398)"

- src/components/hvorfor-soknad-sykepenger/hvorfor-soknad-sykepenger-tekster.ts
Endret tittel på ekspand-boks som forteller om hvorfor man må søke om sykepenger.
> Endre tittel på expand-boks

- cypress/integration/run-1/delvis-utfylt-reisetilskudd.ts
- cypress/integration/run-1/delvis-utfylt-soknad.ts
- src/components/soknader/teaser/teaser-tekster.ts
- src/components/soknader/teaser/teaser.tsx
- src/data/mock/data/reisetilskudd.ts
- src/data/mock/data/soknader-integration.ts
- src/data/mock/index.ts
- src/utils/url-utils.ts
Markerer delvis utfylte søknader og linker til siste ubesvarte spørsmål.
> Vis delvis utfylt søknad

- src/components/status/statuspanel.tsx
Trengs ikke lenger da avbrutte søknader blir timet ut på lik linje med
nye, men ikke utfylte, søknader.
> Slett logikk for visning av gjenåpningsknapp

- cypress/integration/run-0/arbeidstaker_100.ts
- cypress/integration/run-0/avbrutt_soknad.ts
- package-lock.json
- src/components/avbryt-soknad-modal/avbryt-soknad-modal-tekster.ts
- src/components/avbryt-soknad-modal/avbryt-soknad-modal.less
- src/components/avbryt-soknad-modal/avbryt-soknad-modal.tsx
Reverts navikt/sykepengesok#449
> Revert "Labs avbryt survey"

- cypress/integration/run-0/arbeidstaker_100.ts
- src/components/kvittering/kvittering-side.less
- src/components/kvittering/kvittering-side.tsx
- src/components/kvittering/kvittering-tekster.ts
Avslutt-knapp heter nå Ferdig, og tar deg til Ditt Sykefravær i stedet for Ditt NAV.
> Endre Avslutt til Ferdig

- src/auth/ErrorMedStatus.ts
- src/components/avbryt-soknad-modal/avbryt-soknad.ts
- src/components/endreknapp/endreknapp.tsx
- src/components/ettersending/ettersending.tsx
- src/components/filopplaster/drag-and-drop/drag-and-drop.tsx
- src/components/filopplaster/kvittering-modal/opplasting-form.tsx
- src/components/kvittering/arbeidstaker.tsx
- src/components/kvittering/kontonummer/kontonummer.tsx
- src/components/opprett-utland/opprett-utland.tsx
- src/components/slettknapp/slettknapp.tsx
- src/components/soknader/avbryt/gjenapneknapp.tsx
- src/components/sporsmal/sporsmal-form/sporsmal-form.tsx
- src/data/data-fetcher.tsx
- src/data/rest/utils.ts
- src/utils/fetch.ts
- src/utils/logger.ts
Samkjørt logging og feilhåndtering ved kall til fetchMedRequestId og laget egen metode som returnerer JSON.
> Flytt feilhåndtering ved fetch til ett sted

- src/components/avbryt-soknad-modal/avbryt-soknad.ts
- src/components/endreknapp/endreknapp.tsx
- src/components/ettersending/ettersending.tsx
- src/components/filopplaster/drag-and-drop/drag-and-drop.tsx
- src/components/filopplaster/kvittering-modal/opplasting-form.tsx
- src/components/kvittering/arbeidstaker.tsx
- src/components/opprett-utland/opprett-utland.tsx
- src/components/slettknapp/slettknapp.tsx
- src/components/soknader/avbryt/gjenapneknapp.tsx
- src/components/sporsmal/sporsmal-form/sporsmal-form.tsx
- src/data/data-fetcher.tsx
- src/utils/fetch.ts
- src/utils/tekster.ts
Error skaper unødvendig mye støy i loggene.
> Logg 'warn' i stedet for 'error'

- next.config.js
- src/components/kvittering/harSvartJa.ts
- src/components/kvittering/kvittering-side.tsx
This reverts commit d99bde273b4a8cdf60583218a422de2290c3dba9.
> Slå av UxSignals for folk som nylig har korrigert en søknad

- next.config.js
Trengs for kvitteringer i gradert reisetilskudd.
> Legg til blog: i CSP for img-src

- src/components/kvittering/kvittering-side.tsx
This reverts commit cd724a3320f3d12910cf654f92e7a8fc6f9722e5.
> Revert "Skru av uxsignals (#2085)"

- src/components/sporsmal/bekreftelsespunkter/bekreftelsespunkter-selvstendig-naeringsdrivende-tekster.ts
- src/components/sporsmal/typer/kulepunkter.tsx
- src/data/mock/data/soknad/frilanser.ts
- src/data/mock/data/soknad/naringsdrivende.ts
> Legger til kulepunkter for selvstendig næringsdrivende og frilansere

- cypress/e2e/run-0/yrkesskade.cy.ts
- cypress/e2e/run-3/veldig_lang_soknad.cy.ts
- src/components/hjelpetekster/ekspanderbar-hjelp/yrkesskade-hjelp-body.tsx
- src/components/hjelpetekster/yrkesskade-info.tsx
- src/components/soknad/soknaden-tekster.ts
- src/components/sporsmal/typer/ja-nei-stor.tsx
- src/components/sporsmal/yrkesskade-bulletpoints.tsx
- src/data/mock/data/sporsmal/yrkesskade-v2.ts
- Endre yrkeskade til 2.5 versjon
- Tekstendring yrkesskade
> Tekstendringer på yrkesskade

- src/components/soknad/soknaden.tsx
> setter riktig feedbackId for survey

- cypress/e2e/run-2/opprett_opphold_utland_landingsside.cy.ts
- cypress/support/e2e.ts
og sjekker uu kun på localhost sider
> mocker kallet til sykefravaer demo

- cypress/e2e/run-3/flexjar.cy.ts
- src/components/flexjar/flexjar-felles.tsx
- src/components/flexjar/flexjar-kvittering.tsx
- src/components/flexjar/flexjar-sporsmal.tsx
> Flexjar - endre tekst

- .github/workflows/workflow.yml
- src/pages/_document.page.tsx
- src/utils/environment.ts
- **Test e2e build uten dekoratør**
- **e2ebuild**
> Ingen dekoratøre i e2e

- src/components/avbryt-soknad-modal/avbryt-soknad-modal.tsx
Reverts navikt/sykepengesoknad-frontend#3259
> Revert "Fjerner mulighet for å avbryte friskmeldt til arbeidsformidling søknader"
